### ISSUE TITLE
It has bugs with new updates in Dependencies.

### ISSUE THREAD

**Issue by abdulnine7** [IonicaBizau/github-portfolio#13]
# Not Working

**Comment by IonicaBizau** [comment]
Can you please add more details?

**Comment by abdulnine7** [comment]
# Error 1 
```
JohnnysStatic.setStaticServer({root: "./public"});
              ^

TypeError: JohnnysStatic.setStaticServer is not a function
    at Object.<anonymous> (/home/flintstone/nodeProjects/github-portfolio/server.js:6:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

```

The ``` setStaticServer ``` function is renamed to ``` server ``` in new update of johnnys-node-static module.

# Error 2
```
/home/flintstone/nodeProjects/github-portfolio/server.js:11
var converter = new Showdown.converter();
                ^

TypeError: Showdown.converter is not a constructor
    at Object.<anonymous> (/home/flintstone/nodeProjects/github-portfolio/server.js:11:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

```

**Comment by Alynva** [comment]
This is because you doesn't specify the version of yours dependencies. **Stop** doing that.

**Comment by IonicaBizau** [comment]
Indeed! 👍 

Greetings from Curitiba. 😄

**Comment by abdulnine7** [comment]
Yes, This is because of the latest version consideration while making the repository.
`
"dependencies": {
    "johnnys-node-static": "*",
    "showdown": "*"
  }
`
